spring:
  application:
    name: virement-service

  config:
    import: optional:configserver:http://localhost:8888
    fail-fast: true

  datasource:
    url: jdbc:mysql://localhost:3306/virements-db
    username: root
    password: toor

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

server:
  port: 9081

spring.cloud:
  discovery:
    enabled: true

